name: Test Upload Script

on: [push]

jobs:
  test-upload:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.1'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gigafile
        pip list
        pip show gigafile

    - name: Upload files to Gigafile
      run: |
        $filePaths = @("./test1.txt", "./test2.txt")
        foreach ($filePath in $filePaths) {
          python upload_to_gigafile.py $filePath
        }
      shell: pwsh
